### ISSUE TITLE
Breaking change in minor version

### ISSUE THREAD

**Issue by ursuleacv** [plivo/plivo-php#195]
In this pull request #191 from  v4.13.0
was introduced a breaking change. It should not be in a minor version

```
      +  "php": ">=7.1.0",
```

[https://github.com/plivo/plivo-php/commit/93a29d174d8fd741493aaffc3d16aba765c1b6a6](url)

**Comment by huzaif-plivo** [comment]
@ursuleacv We updated our SDK with the base PHP version as the older versions eradicated a few key functionalities that might break the entire SDK. It was not updated as a major release as we were not receiving requests with older PHP versions. Feel free to contact our [support team](https://support.plivo.com/hc/en-us) if you are facing any issues so that we can assist you accordingly.
